<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <Import Project=".\Sts2PathDiscovery.props"/>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable> <!--Makes code analysis regarding null values stricter.-->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>packages/**</DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
        <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
        <LangVersion>default</LangVersion>
        <ModManifest>$(AssemblyName).json</ModManifest>
        <ResourcesDir>$(AssemblyName)Resources</ResourcesDir>
        <PckPackerSourceDir>$(ResourcesDir)/</PckPackerSourceDir>
        <SteamWorkshopModPath>$(SteamWorkshopUploaderPath)$(MSBuildProjectName)</SteamWorkshopModPath>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Diasble architecture mismatch warning; mods are ideally built for all platforms (MSIL)
             while your local StS2 version will be for your specific platform. -->
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup> <!--Allows access to originally private/protected members but may (unlikely to) cause errors.-->
        <Publicize Include="sts2" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.3.5" PrivateAssets="All" />
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="All"/>
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="*"/>
        <PackageReference Include="BSchneppe.StS2.PckPacker" Version="0.1.1" PrivateAssets="All" /> 
        <AdditionalFiles Include="$(ResourcesDir)/localization/**/*.json"/> <!-- Used by analyzer -->
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="$(ResourcesDir)/**"/>
        <Compile Remove="materials/**"/>
        <Compile Remove="shaders/**"/>
        <Compile Remove="images/**"/>
        <Compile Remove="audio/**"/>
        <EmbeddedResource Remove="$(ResourcesDir)/**"/>
        <EmbeddedResource Remove="materials/**"/>
        <EmbeddedResource Remove="shaders/**"/>
        <EmbeddedResource Remove="images/**"/>
        <EmbeddedResource Remove="audio/**"/>
    </ItemGroup>

    <ItemGroup>
        <None Condition="Exists('Directory.Build.props')" Include="Directory.Build.props"/>
        <None Include=".gitignore"/>
        <None Include="$(ModManifest)"/>
        <None Include="project.godot"/>
        <None Include="$(ResourcesDir)/**"/>
    </ItemGroup>

    <Target Name="CheckDependencyPaths">
        <Error Text="Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
               Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')"/>
    </Target>

    <ItemGroup>
        <GodotResourceFiles Include="CharMod/**"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="README.md"/>
        <Content Include="Sts2PathDiscovery.props"/>
    </ItemGroup>
    
    <!-- Custom Build Targets -->
    
    <Target Name="GetVersion">
        <PropertyGroup>
            <ManifestContent>$([System.IO.File]::ReadAllText('$(AssemblyName).json'))</ManifestContent>
            <Version>$([System.Text.RegularExpressions.Regex]::Match('$(ManifestContent)', '"version":\s*"v([^"]+)').Groups[1].Value)</Version>
        </PropertyGroup>

        <CreateProperty Value="$(Version)">
            <Output TaskParameter="Value" PropertyName="Version" />
        </CreateProperty>
        
        <CreateProperty Value="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version)">
            <Output TaskParameter="Value" PropertyName="BuildOutputBundleDir" />
        </CreateProperty>
    </Target>

    <!-- Collect Mod Files -->
    
    <Target Name="CleanOut">
        <Message Text="Cleaning 'out' dir" Importance="high"/>
        <RemoveDir Directories="$(MSBuildProjectDirectory)/out"/>
    </Target>

    <Target Name="Collect" AfterTargets="PackPck" DependsOnTargets="CleanOut;GetVersion"
            Condition="Exists('$(TargetPath)') And Exists('$(ModManifest)') And Exists('$(PckPackerOutputPath)') And '$(PckPackerSkipped)' != 'true'">
        <Message Text="Collecting .dll, .json, and .pck for v$(Version)" Importance="high"/>

        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BuildOutputBundleDir)"/>
        <Copy SourceFiles="$(ModManifest)" DestinationFolder="$(BuildOutputBundleDir)"/>
        <Copy SourceFiles="$(PckPackerOutputPath)" DestinationFolder="$(BuildOutputBundleDir)"/>
    </Target>

    <!-- Move Mod Files to Mods Folder -->
    
    <Target Name="RemoveOldModVersion">
        <ItemGroup>
            <OldModDir Include="$([System.IO.Directory]::GetDirectories('$(ModsPath)', '$(MSBuildProjectName)*'))"/>
        </ItemGroup>
        
        <Message Text="Deleting old mod dir: @(OldModDir)" Importance="high"/>
        <RemoveDir Directories="@(OldModDir)"/>
    </Target>
    
    <Target Name="CopyToMods" AfterTargets="Collect" DependsOnTargets="RemoveOldModVersion;GetVersion">
        <ItemGroup>
            <ModFiles Include="$(BuildOutputBundleDir)/**"/>
        </ItemGroup>
        
        <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModsPath)$(MSBuildProjectName).$(Version)/%(RecursiveDir)"/>
    </Target>

    <!-- Create Steam Release -->

    <Target Name="RemoveOldSteamWorkshopModFolder">
        <ItemGroup>
            <ContentFiles Include="$(SteamWorkshopModPath)/content/*.*"/>
            <ContentDirs Include="$([System.IO.Directory]::GetDirectories('$(SteamWorkshopModPath)/content/', '*'))"/>
        </ItemGroup>
        
        <Message Text="Deleting old uploader content: @(ContentFiles), @(ContentDirs)" Importance="high"/>
        <Delete Files="@(ContentFiles)"/>
        <RemoveDir Directories="@(ContentDirs)"/>
    </Target>
    
    <Target Name="CopyToSteamWorkshopUploader" DependsOnTargets="RemoveOldSteamWorkshopModFolder;GetVersion">
        <Error Text="Cannot copy to Steam Workshop Uploader: Bundle directory '$(BuildOutputBundleDir)' does not exist, make sure to build first"
               Condition="!Exists('$(BuildOutputBundleDir)')"/>
        
        <ItemGroup>
            <ModFiles Include="$(BuildOutputBundleDir)/**"/>
        </ItemGroup>
        
        <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(SteamWorkshopModPath)/content/$(MSBuildProjectName).$(Version)/%(RecursiveDir)"/>
    </Target>
    
    <Target Name="UpdateSteamWorkshopChangelog" DependsOnTargets="CopyToSteamWorkshopUploader" Condition="Exists('$(SteamWorkshopModPath)')">
        <PropertyGroup>
            <ChangelogFile>$(MSBuildProjectDirectory)/out/CHANGELOG.bbcode</ChangelogFile>
        </PropertyGroup>
        
        <Exec Command="git-cliff.exe --latest --config &quot;.config/cliff.bbcode.toml&quot; --output &quot;$(ChangelogFile)&quot;"/>
        
        <Message Text="Generated changelog at: $(ChangelogFile)" Importance="high"/>
        
        <Exec Command="pwsh -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)/UpdateSteamWorkshopJson.ps1&quot; -WorkshopPath &quot;$(SteamWorkshopModPath)/workshop.json&quot; -ChangelogPath &quot;$(ChangelogFile)&quot;"
              Condition="Exists('$(ChangelogFile)')"/>
    </Target>
        
    <!-- Run Target -->
    <Target Name="UploadToSteamWorkshop" DependsOnTargets="UpdateSteamWorkshopChangelog" Condition="Exists('$(SteamWorkshopModPath)')">
        <Exec Command="$(SteamWorkshopUploaderPath)ModUploader.exe upload -w &quot;$(SteamWorkshopUploaderPath)$(MSBuildProjectName)&quot;"/>
    </Target>
    
    <!-- Create Github Release -->

    <!-- Run Target -->
    <Target Name="BumpVersionPatch">
        <MSBuild Projects="$(MSBuildProjectFile)"
                 Targets="BumpVersion"
                 Properties="VersionPart=PATCH"/>
    </Target>

    <!-- Run Target -->
    <Target Name="BumpVersionMinor">
        <MSBuild Projects="$(MSBuildProjectFile)"
                 Targets="BumpVersion"
                 Properties="VersionPart=MINOR"/>
    </Target>

    <!-- Run Target -->
    <Target Name="BumpVersionMajor">
        <MSBuild Projects="$(MSBuildProjectFile)"
                 Targets="BumpVersion"
                 Properties="VersionPart=MAJOR"/>
    </Target>

    <Target Name="BumpVersion" Condition="Exists('$(ModManifest)')">
        <Exec Command="pwsh -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)/BumpVersion.ps1&quot; $(VersionPart) &quot;$(ModManifest)&quot;"
              ContinueOnError="false"/>
    </Target>
    
    <Target Name="GitPushVersionBump" AfterTargets="BumpVersion" DependsOnTargets="GetVersion" Condition="Exists('$(ModManifest)')">
        <Exec Command="git commit -m &quot;Bump version to v$(Version)&quot; &quot;$(ModManifest)&quot;"/>
        <Exec Command="git tag -f v$(Version)"/>
        <Exec Command="git push origin v$(Version)"/>
        <Exec Command="git push origin master"/>
    </Target>

    <Target Name="ZipArchive" DependsOnTargets="GetVersion;Collect">
        <Error Text="Cannot create Zip archive: Bundle directory '$(BuildOutputBundleDir)' does not exist, make sure to build first"
               Condition="!Exists('$(BuildOutputBundleDir)')"/>
        
        <ZipDirectory SourceDirectory="$(BuildOutputBundleDir)"
                      DestinationFile="$(BuildOutputBundleDir).zip"
                      Overwrite="true"/>
    </Target>

    <Target Name="GenerateLatestChangelog">
        <PropertyGroup>
            <ChangelogFile>$(MSBuildProjectDirectory)/out/CHANGELOG.md</ChangelogFile>
        </PropertyGroup>

        <Exec Command="git-cliff.exe --latest --config &quot;.config/cliff.md.toml&quot; --output &quot;$(ChangelogFile)&quot;"/>

        <Message Text="Generated changelog at: $(ChangelogFile)" Importance="high"/>

        <CreateProperty Value="$(ChangelogFile)">
            <Output TaskParameter="Value" PropertyName="ChangelogFileMarkdown" />
        </CreateProperty>
    </Target>
    
    <Target Name="GithubRelease" AfterTargets="GitPushVersionBump" DependsOnTargets="GetVersion;ZipArchive;GenerateLatestChangelog">
        <Error Text="Cannot create GitHub release: Changelog file '$(ChangelogFileMarkdown)' does not exist"
               Condition="!Exists('$(ChangelogFileMarkdown)')"/>
        <Error Text="Cannot create GitHub release: Zip archive '$(BuildOutputBundleDir).zip' does not exist"
               Condition="!Exists('$(BuildOutputBundleDir).zip')"/>

        <Exec Command="gh release create v$(Version) --notes-file &quot;$(ChangelogFileMarkdown)&quot; --title &quot;v$(Version)&quot; --fail-on-no-commits &quot;$(BuildOutputBundleDir).zip&quot; &quot;$(BuildOutputBundleDir)/*&quot;"/>
    </Target>

    <!-- Publish Release -->
    
    <!-- Run Target -->
    <Target Name="PublishPatchRelease">
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="BumpVersionPatch"/>
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="UploadToSteamWorkshop"/>
    </Target>

    <!-- Run Target -->
    <Target Name="PublishMinorRelease">
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="BumpVersionMinor"/>
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="UploadToSteamWorkshop"/>
    </Target>

    <!-- Run Target -->
    <Target Name="PublishMajorRelease">
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="BumpVersionMajor"/>
        <MSBuild Projects="$(MSBuildProjectFile)" Targets="UploadToSteamWorkshop"/>
    </Target>
</Project>