<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <Import Project=".\Sts2PathDiscovery.props"/>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable> <!--Makes code analysis regarding null values stricter.-->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>packages/**</DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
        <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
        <LangVersion>default</LangVersion>
        <ModManifest>$(AssemblyName).json</ModManifest>
        <ResourcesDir>$(AssemblyName)Resources</ResourcesDir>
        <PckPackerSourceDir>$(ResourcesDir)/</PckPackerSourceDir>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Diasble architecture mismatch warning; mods are ideally built for all platforms (MSIL)
             while your local StS2 version will be for your specific platform. -->
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup> <!--Allows access to originally private/protected members but may (unlikely to) cause errors.-->
        <Publicize Include="sts2" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.2.1" PrivateAssets="All" />
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="All"/>
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="*"/>
        <PackageReference Include="BSchneppe.StS2.PckPacker" Version="0.1.1" PrivateAssets="All" /> 
        <AdditionalFiles Include="$(ResourcesDir)/localization/**/*.json"/> <!-- Used by analyzer -->
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="$(ResourcesDir)/**"/>
        <Compile Remove="materials/**"/>
        <Compile Remove="shaders/**"/>
        <Compile Remove="images/**"/>
        <EmbeddedResource Remove="$(ResourcesDir)/**"/>
        <EmbeddedResource Remove="materials/**"/>
        <EmbeddedResource Remove="shaders/**"/>
        <EmbeddedResource Remove="images/**"/>
    </ItemGroup>

    <ItemGroup>
        <None Condition="Exists('Directory.Build.props')" Include="Directory.Build.props"/>
        <None Include=".gitignore"/>
        <None Include="$(ModManifest)"/>
        <None Include="project.godot"/>
        <None Include="$(ResourcesDir)/**"/>
    </ItemGroup>

    <Target Name="CheckDependencyPaths">
        <Error Text="Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
               Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')"/>
    </Target>

    <ItemGroup>
        <GodotResourceFiles Include="CharMod/**"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="README.md"/>
        <Content Include="Sts2PathDiscovery.props"/>
    </ItemGroup>
    
    <Target Name="CleanOut" BeforeTargets="Collect">
        <Message Text="Cleaning 'out' dir" Importance="high"/>
        <RemoveDir Directories="$(MSBuildProjectDirectory)/out"/>
    </Target>
    
    <Target Name="Collect" AfterTargets="PackPck">
        <PropertyGroup>
            <ManifestContent>$([System.IO.File]::ReadAllText('$(AssemblyName).json'))</ManifestContent>
            <Version>$([System.Text.RegularExpressions.Regex]::Match('$(ManifestContent)', '"version":\s*"v([^"]+)').Groups[1].Value)</Version>
        </PropertyGroup>
        
        <CreateProperty Value="$(Version)">
            <Output TaskParameter="Value" PropertyName="Version" />
        </CreateProperty>

        <Message Text="Collecting .dll, .json, and .pck for v$(Version)" Importance="high"/>

        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version)"/>
        <Copy SourceFiles="$(ModManifest)" DestinationFolder="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version)"/>
        <Copy SourceFiles="$(PckPackerOutputPath)"
              DestinationFolder="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version)"
              Condition="Exists('$(PckPackerOutputPath)') And '$(PckPackerSkipped)' != 'true'"/>
    </Target>
    
    <Target Name="RemoveOldMod" BeforeTargets="CopyToMods">
        <ItemGroup>
            <OldModDir Include="$([System.IO.Directory]::GetDirectories('$(ModsPath)', '$(MSBuildProjectName)*'))"/>
        </ItemGroup>
        
        <Message Text="Deleting old mod dir: @(OldModDir)" Importance="high"/>
        <RemoveDir Directories="@(OldModDir)"/>
    </Target>
    
    <Target Name="CopyToMods" AfterTargets="Collect">
        <ItemGroup>
            <ModFiles Include="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version)/**"/>
        </ItemGroup>
        
        <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModsPath)$(MSBuildProjectName).$(Version)/%(RecursiveDir)"/>
    </Target>
    
    <Target Name="Zip" AfterTargets="Collect">
        <ZipDirectory SourceDirectory="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version)" 
                      DestinationFile="$(MSBuildProjectDirectory)/out/$(MSBuildProjectName).$(Version).zip"
                      Overwrite="true"/>
    </Target>
</Project>